### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/tech-amp-theme#1]
- [ ] Crafting

- [x] Line should have the gaping http://take.ms/g2nZn

- [x] First post should not have the border http://take.ms/g2nZn

- [x] It should be in the one line: http://take.ms/gMKEU

- [x] Arrows http://take.ms/jDSio

- [x] amp-sidebar can only be the parent of the body: http://take.ms/x2Bl8 - make sure it's not in the div.
- [x] Reduce 3 Parent div's to 1 Parent div: http://take.ms/jFUmV

- [x] The leave a comment button should not be full width: http://take.ms/DhQjR

- [x] Footer Like: http://take.ms/sVdtn
- [ ] Menu Should have the logo visible:  http://take.ms/qKjaW
- [ ] If we have more categories, then it should look correct: http://take.ms/JEo1T

----
Ajeet:

### amp_loop_author

- [x]  amp_loop_author by default should not display the all the author information: http://take.ms/5GQDl

- [x] When we add the amp_loop_author(); it should display only the name.

- [x] It should have Three Sub values:

```
$args = array(
// Display the Avatar show/hide. By default, it will be hide
'avatar' => 'show', 

// Display the Avatar Image. By default, it should be 40px.
'avatar_size' => '40px', 

// Ability to add the custom Class. By default, there won't be any custom class. Once it's added, it should be added next to amp-author class that is already available in that parent div.
'class'=>'CUSTOM_CLASS',
);
```

- [x] amp_loop_author should not display any date: http://take.ms/z83Cm

- [x] In the end: If we add amp_loop_author(); it will only display the Author name. The Word "BY" "Posted by" or "Published By" will be added manually. Rest of the things can be added from the arrays.

### amp_loop_date

- [ ] We already have this amp_loop_date, but by default it shows the date like "3 Months Ago", which is perfectly fine. We need an ability to show the date in the Traditional WP way as well which looks like " July 14, 2017 10:03 am". 
So, we need to create an array option.

```
// We need two options:   'format'=> "ago" &   'format'=> "traditional",

$args = array( 'format'=> 'traditional' );
amp_loop_date($args); 
```

**Comment by RajuJeelaga** [comment]
- [ ] Add The notification, that, when any one install the theme, It shows the Notification like, These Theme Require an AMP --- refer ahmedkaludi/accelerated-mobile-pages#1421
